Run: Feb12_2001
     Default Description: Yes
     Log File: Feb12_2001.log
     DSS File: Feb12_2001.dss
     Is Save Spatial Results: No
     Last Modified Date: 31 January 2022
     Last Modified Time: 16:32:32
     Last Execution Date: 1 February 2022
     Last Execution Time: 20:25:44
     Basin: Basin 1
     Precip: Feb12_2001
     Control: Feb12_2001
     Save State Type: None
     Time-Series Output: Save All
End:

