Run: Feb12_2001
     Default Description: Yes
     Log File: Feb12_2001.log
     DSS File: Feb12_2001.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 February 2022
     Last Modified Time: 14:28:49
     Last Execution Date: 2 February 2022
     Last Execution Time: 14:29:27
     Basin: Basin 1
     Precip: Feb12_2001
     Control: Feb12_2001
     Save State Type: None
     Time-Series Output: Save All
End:

